### ISSUE TITLE
Event result (webhooks)

### ISSUE THREAD

**Issue by MyWay** [caronc/apprise-api#101]
Would it be possible to add support for events? E.g. after a request has been handled by apprise, we could receive a webhook event with the result, if configured.

**Comment by caronc** [comment]
Seems like a good idea

**Comment by caronc** [comment]
What kind of information do you expect to find within the payload of this webhook?

**Comment by MyWay** [comment]
What about a status and, in case it failed, an error  message?

**Comment by caronc** [comment]
I made a lot of progress on this.  The test cases are currently failing on the Apprise-API version only because it depends on some enhancements made the underlining Apprise library.

Once those are pushed into the next official release, the tests cases here will pass and you'll have your web-hook support.  I'll leave this ticket open until things are ready to go.

**Comment by caronc** [comment]
Merged; Apprise v1.6.0 was released. If you us `:latest` you'll get this new enhancement.  But i'll do an Apprise API official release shortly too to update the main build.

Closing this issue off as done :rocket:
