### ISSUE TITLE
Docker image for ARM ?

### ISSUE THREAD

**Issue by sunny5055** [caronc/apprise-api#13]
:question: **Question**

Tried to build the docker on arm but does not seem to work. 
Getting exec format error. 

Tried to run directly still got error.

  _File "manage.py", line 44
    ) from exc
         ^
SyntaxError: invalid syntax_

Is there a docker image for arm ? or anything need to be changed before building the docker image ?
No issue with the CLI its working perfect. Just issue with getting up the api 

Can you advise me whats is the best way to get this running.

**Comment by caronc** [comment]
You definitely stumped me on this one. I'm still new to Docker; what you see so far was just a lot of great help from [another kind community user](https://github.com/caronc/apprise/issues/191) coaching me.

I will look into see if it's possible to build the container as ARM.  It's possible it's related to the s6 program i pull in (since it's already compiled as a binary)  Perhaps i need to add some kind of logic around that (or create another docker container that calls in the ARM version)...  I will look into this and hopefully get back to you with some positive information.

**Comment by sunny5055** [comment]
Thank you very much.. While i wait for your update.. i will try if i can get this up running somehow.

**Comment by sunny5055** [comment]
Hi, Just revisited this after long time and managed to compile the docker build for ARM. 
Its working now.

**Comment by caronc** [comment]
That's awesome.  If you got it building on your own, do you mind if i close this?

**Comment by sunny5055** [comment]
Yes we can close this . thanks
