### ISSUE TITLE
How do you build your Docker images

### ISSUE THREAD

**Issue by zaherg** [caronc/apprise-api#21]
:question: **Question**
I was wondering about the way you build your docker images, is there any automated script or service you use?

if there is, can you add support to ARM devices? if there is any help I can provide let me know

Thanks

**Comment by caronc** [comment]
Hi @zaherg ,

You're actually the second person to ask me this (first was at #13) and i wasn't much help there either. That said @GeorgeGedox managed to get a working ARM Apprise API container working; he was kind enough to share a screenshot of this on Discord this morning with me.  He made it clear that he wanted to do a bit more testing and then _possibly_ do a pull request.

I'm still new with Docker myself so I don't want to pretend to know what I'm doing in my response here to you.  But I can tell you (knowing the backed very, very well) that if you only need to use the API (and do not need access to the interactive website at all), you can use the **[Dockerfile-gunicorn file](https://github.com/caronc/apprise-api/blob/master/Dockerfile-gunicorn)** to build an `ARM` container.

If you also need the website then I'll need to get back to you.   [Django makes it pretty clear that I shouldn't use their static serving feature for production use](https://docs.djangoproject.com/en/3.1/ref/contrib/staticfiles/#static-file-development-view). This is specifically the reason why the Nginx portion exists. But for it to live in the same container I had to use the magic of **[S6 Overlay](https://github.com/just-containers/s6-overlay)** which is where your container will break with ARM deployments. 

Possible solutions right now are:
- Use an environment variable that turns on the Development Django file serving so that everything can be hosted via gunicorn ( _thus work with all architectures_)
- Find a way to pull in the correct S6 Overlay package dynamically based on the architecture it's being built for.
- Wait for @GeorgeGedox who's screenshots made me thirsty to solve this problem for you (all credit to him of course).  I'm not sure if he chose one of the above routes or came up with another.

Sorry to talk so much; I'm actually polling you (or anyone else reading this) for feedback. :slightly_smiling_face:

**Comment by zaherg** [comment]
Hey @caronc , I am more interested in the API side more than the website itself, as I'll be testing it locally and the GUI is not that much important.

I'll do a small tests and get back to you soon, if you need help with docker I am more happy to help.

I'll close this ticket for now, and I'll keep my eye on the repo ;)
