### ISSUE TITLE
[Q] is there a way to disable the dashboard

### ISSUE THREAD

**Issue by zaherg** [caronc/apprise-api#27]
:question: **Question**
I was wondering if there is any way to disable the dashboard and just run the API

thanks

**Comment by caronc** [comment]
Since #24; yes (a very recent code commit/merge).  Make sure you have the latest docker container and set the [environment variable](https://github.com/caronc/apprise-api#environment-variables): `APPRISE_STATEFUL_MODE=disabled`

That should do it.  The website will still be there but all stateful transactions will not work and/or be accessible.

**Comment by zaherg** [comment]
Amazing, thanks @caronc
