### ISSUE TITLE
Can't send notifications to email

### ISSUE THREAD

**Issue by user1902** [caronc/apprise-api#29]
Not able to send the notification to email.
In response am getting "One or more notification could not be sent."
the Input is :
{
"urls": "mailto://abc:abc123@gmail.com/abc@abc.in",
"title": "test message",
"body": "test notifiction"
}
And in command line its coming
Failed Dependency: /notify
[11/Nov/2020 12:04:12] "POST /notify HTTP/1.1" 424 43

**Comment by caronc** [comment]
Hi,

Try adding `-vvv` to your command line call; that should reveal to you much more details that will help you determine what is going wrong here:
```bash
apprise -vvv -t "test message" -b "test notification" \
   "mailto://abc:abc123@gmail.com/abc@abc.in"
```
If you're using gmail, the 2 Step Verification Process (if you're using it) will be required to generate an app-password [from here](https://security.google.com/settings/security/apppasswords) that you can use in the `{password}` field.

Your Apprise URL otherwise looks like it's formed well; so it might be just a login/pass issue at this time.  If your password has special characters in it, this can be a problem too.  Check out [this link here](https://github.com/caronc/apprise/wiki/Troubleshooting#special-characters-and-url-conflicts) on troubleshooting special characters.

Good luck! Let me know if you have any questions :slightly_smiling_face:

**Comment by user1902** [comment]
Thanks for your response.

For email this condition is giving false :
if not py3compat.asyncio.notify(coroutines, debug=self.debug):

and it returning false to the status. So the notification is not sending.

**Comment by caronc** [comment]
I believe you are the same person who also reached out to me via email. The issue turned out to having not generated an App Password with Google. 

Are you okay if I close off this ticket?

**Comment by user1902** [comment]
yea sure
