### ISSUE TITLE
Unable to save urls through dashboard

### ISSUE THREAD

**Issue by BiswajitTri** [caronc/apprise-api#31]
:question: **Question**

![Screenshot from 2020-12-23 14-31-13](https://user-images.githubusercontent.com/75363869/102979171-b2c38380-452b-11eb-985c-a28580bb39da.png)

**Comment by caronc** [comment]
Hi,
The problem is that under the hood, the Apprise API doesn't run as `root`.  It runs as `www-data` inside the container.  So the path you mounted your `/config` too simply doesn't have access to write to it (it's a permission issue).

A simple fix could be to change the permission to 777 on your `/config` directory so it will save the data.  

Let me know if you get it going! :slightly_smiling_face:

**Comment by eresonance** [comment]
Yep, debug log:
```
Internal Server Error: /add/apprise
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/apprise/webapp/api/views.py", line 213, in post
    if not ConfigCache.put(
  File "/opt/apprise/webapp/api/utils.py", line 123, in put
    os.makedirs(path, exist_ok=True)
  File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/config/27'
127.0.0.1 - - [29/Dec/2020:10:34:22 -0600] "POST /add/apprise HTTP/1.0" 500 87136 "http://[redacted]/cfg/apprise" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0"
```

Fixed it via `chmod 777 /config` connected to the console of the docker image. @caronc are you able to fix this in your Dockerfile?

**Comment by caronc** [comment]
I'm glad you figured it out, it all stems from [this pull request](https://github.com/caronc/apprise-api/pull/28).  By default everything used to run as **root** which definitely has access the `config` directory (error free).  This was removed to eliminate any _potential_ security risks from running as a super-user.  Having the container run as a non-root user just adds that extra safety net.

But I could probably at least add better documentation around this as you're not the first person to have this problem. :slightly_smiling_face:

**Comment by hutch0** [comment]
Unless I missed it somewhere, can this be added to the documentation? I was banging my head against the wall for days on this. Almost gave up on Apprise altogether. Within 10 minutes of realizing I should look for an issue here under apprise-api instead of general apprise, I was up and running and had Matrix notifications sent any time there's a login to any of my servers over SSH. Fantastic work @caronc !

**Comment by caronc** [comment]
@hutch0: You didn't miss it, this part is very poorly documented. I'm not sure what the best solution is here. Revert back to the `root` user so that it works for everyone always (but isn't necessarily the right approach). The `chmod 777` is also not the best solution either. 

Ideally it should be a `chmod 770` and a local `usermod` call to add only those you trust into the group (locally). This would protect the information from prying eyes.

**Comment by mariomare22** [comment]
What can really help is imho to throw a specific error such as  "could not write config file" or "you don't have permission to save the configuration"

**Comment by caronc** [comment]
Your point is very valid. I thought i already had that in place to be honest and... well...  I kinda/sorta did.  But due to a bug on the front end, I was never actually displaying the notice in question. I fixed it [here](https://github.com/caronc/apprise-api/pull/44/commits/e0d1f9f7b8c1986fe05591963101241e1d042413) just now and additioanlly cleaned it up a bit.  Does the wording seem okay? Would you think this is satisfactory in addition to the documentation in the `README.md` identified [here](https://github.com/caronc/apprise-api/pull/44/commits/3ee3267ad71e44916d699d5d967880b27fb6f1ef)?

**Comment by mariomare22** [comment]
sounds fantastic! I will test the ad-hoc user creation which best fits production environments!

thanks a lot
