### ISSUE TITLE
File attachments via API

### ISSUE THREAD

**Issue by mariomare22** [caronc/apprise-api#39]
:question: **Question**
Is the a possibility beides sending a picture to telegram to send a log file?

Thanks

**Comment by mariomare22** [comment]
I think I found a workaround:
`docker exec apprise apprise -t "my log" -b "see attached" --attach /config/test.txt -g tg_grp --config=http://localhost:8080/get/zfstg`

This works but implies that I have previously copied the log file into the container or I have mounted a volume on the host.
Thanks!

**Comment by caronc** [comment]
I'm glad you found a workaround. If you want to take that approach, you could add `--mount` and mount stuff to be available inside your container for messaging purposes that exist outside ([see here](https://docs.docker.com/storage/volumes/)).

```bash 
$ docker run -d \
  --name=apprise \
  --mount source=/path/on/local/filesystem,destination=/path/on/docker/filesysteml,readonly \
 ...
```

That way you don't need to use the `COPY` directive.  You can just access whatever is current that you popped into your share.

**Comment by mariomare22** [comment]
Yup this is what I am doing! closed for me, Thank you

**Comment by schklom** [comment]
@caronc 
> To add attachment support adds an element of Denial of Service since you can technically post a lot and fill the file-system

Not necessarily. Write a warning in capital letters and let the feature be disabled by default if you want, but I personally do not mind this attack vector because I restrict the API for my personal use (basic auth on the reverse-proxy).

I have a feeling I am far from the only person who only uses Apprise for themselves.

If the day comes that my username and password for basic auth are leaked, it means they will have access to all my other passwords, and a Denial of Service will be the least of my worries.

**Comment by caronc** [comment]
Will reopen for reconsideration
