### ISSUE TITLE
Reverse Proxy with SWAG?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [caronc/apprise-api#71]
:question: **Question**

Does anyone know how to setup a subdomain RP with the [Linuxserver SWAG container](https://hub.docker.com/r/linuxserver/swag)?

I tried creating one:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name apprise.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app apprise;
        set $upstream_port 8000;
        set $upstream_proto https;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

But when i `set $upstream_proto` to `http` i get a `Contradictory scheme headers` error when visiting the URL, and when I `set $upstream_proto` to `https` I get a plain old `502 Bad Gateway` error.

Not sure where to go from here?

**Comment by caronc** [comment]
I'm not going to be too much help here as i've never used swag. But your upstream proto should be `http` not `https`.

**Comment by YouveGotMeowxy** [comment]
@caronc Thanks. So I should set  it to http, and then try to sort out the `Contradictory scheme headers` error, rather than https and try to sort out the 500 error?

**Comment by caronc** [comment]
```nginx
server {
    listen 80;

    server_name apprise.*;
    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        proxy_pass http://your.server.running.apprise:8000;
    }
}
```

Get it workign first with `http`, then start adding more configuration to NginX to secure the hosting.

**Comment by YouveGotMeowxy** [comment]
Hi @caronc 

That looks almost identical to what I posted with the exceptions of you're listening on 80, and I'm listening on 443, and I have the SSL config included.

Are you using the [SWAG](https://hub.docker.com/r/linuxserver/swag) container? If not, can you give it a quick try, it's super simple to setup.

**Comment by caronc** [comment]
@YouveGotMeowxy i feel a bit stupid now.  I didn't realize the whole point was the SSL itself :man_facepalming: .

I guess I was thinking that when dealing with a new nginx instance, just star basic and rule out the SSL completely.  Just create the proxy and nothing more.  SSL adds a lot of overhead and lots more reasons and things to troubleshoot IF setting up for the first time.

Your question is really loaded.... There are lots of things to consider here.  First of all the subdomain
```nginx
    server_name apprise.*;
```

Unless you have DNS server, you'll need to edit your hosts file and make sure you create an entry like:
```
# Don't touch the localhost entry but add to it to support the subdomain
# (only required if you don't have DNS)
127.0.0.1 localhost apprise.localhost
```

Secondly how are you setting up this Nginx Reverse Proxy; it looks like they instruct you to go [here](https://github.com/linuxserver/reverse-proxy-confs)

Apprise could be maybe the same as Bazarr (well not really at all). but the Nginx configuration on the link shared above is closed).  Here is the direct link to their [example](https://github.com/linuxserver/reverse-proxy-confs/blob/master/bazarr.subdomain.conf.sample).

You would perhaps need to just flip the ports around a bit:
```nginx
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name apprise.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app apprise;
        set $upstream_port 8000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
```

The part that throws me off is the last entry
` proxy_pass $upstream_proto://$upstream_app:$upstream_port;`

SWAG assumes you have a container set up running as `apprise`.  Unless you do, this won't work.

When you do your `docker --create`.

Make sure you create a network they can share... so each container you deploy (both the swag and apprise one) add something like `--net apprise-swag`

then you'll need to make sure you create the Apprise container with `--name apprise` so that your reference in the swag initialization connects.

The other thing you can do is set up a `docker-compose.yml` file perhaps and have both containers launch together (i belive docker-compose throws them both in the same network automatically so they can reference one another).

Falling back to the line that throws me off:
` proxy_pass $upstream_proto://$upstream_app:$upstream_port;`

This translates (as you know) to:
`proxy_pass http:/apprise:8000`

So make sure you have a container called `apprise` in your shared `--net` or it can't link.

At least this is where i think things might be going wrong.

**Comment by YouveGotMeowxy** [comment]
> i feel a bit stupid now. I didn't realize the whole point was the SSL itself 🤦‍♂️ .

No worries, lol.

I really appreciate you taking this time out to investigate. :)

I've been using SWAG for probably 2-3 years now, and have something like 80 containers running RP'd through it, so I've got all the basics down (container names, networks, DNS (I use CF). etc.); if you compare the example in my OP with the swag RP you pasted from, the Bazarr RP, they're identical (with the exception of container name and port, and comments removed).  :)

SWAG makes it easy to just add new containers by giving you the samples, then you normally just need to change the container name and port in the RP, and restart SWAG, and about 90% of the time works right out of the box. That's one of the great things about it. For apprise, I just grabbed this: https://github.com/linuxserver/reverse-proxy-confs/blob/master/_template.subdomain.conf.sample

added "apprise" for the container name (which matches the container name I created), added port 8000, and then have been stuck trying to get either http or https working at line 39.

It _seems_ like it should be working, but I get the errors originally mentioned in the OP. :/

**Comment by caronc** [comment]
> Just poking around at that error at the bottom of the log, and not knowing much about coding, but was wondering if apprise uses websockets and/or node?

Nah, it uses neither.

What happens if you reference port 8080?

**Comment by YouveGotMeowxy** [comment]
Strangely, when I use port 8000 w/out the RP and go directly to the IP, i get all the css. As a test when I set that to port 8080 and go to the direct ip I get the same result as when using a RP (no css).

**Comment by caronc** [comment]
Well the good news from your test is you're routing correctly to the right service. Port 8080 is the Django web instance. Port 8000 is the small nginx server in front of it to serve static files.

So perhaps something in my nginx configuration is breaking things for you: https://github.com/caronc/apprise-api/blob/master/apprise_api/etc/nginx.conf

**Comment by STaRDoGG** [comment]
@YouveGotMeowxy This line is the perp: https://github.com/caronc/apprise-api/blob/fea552f7db20362b6f329043455587ea27cbe323/apprise_api/etc/nginx.conf#L52

Comment it out (or delete it) and then mount that file in your docker compose and restart the apprise container:

i.e.

```
- '/opt/docker/configs/apprise/nginx.conf:/opt/apprise/webapp/etc/nginx.conf:ro'
```

**Comment by caronc** [comment]
I updated the master branch; so you should be able to use `:edge` with Docker soon (it's building things now i believe).

**Comment by caronc** [comment]
As a final update, i pushed another Apprise release and rebuilt the Apprise API against it. So `:latest` will also have you covered now

**Comment by YouveGotMeowxy** [comment]
It worked! Thank you so much @STaRDoGG ! And Thank you @caronc for also helping to diagnose ! :D

**Comment by caronc** [comment]
Perfect, I'm going to close this ticket!🚀
